### ISSUE TITLE
SHOW BY ROCKネタがない

### ISSUE THREAD

**Issue by tboffice** [nanaka-inside/C88#11]
- なんとかねじ込んで
- @syucream 
- 8/4まで

**Comment by syucream** [comment]
なんか考えますー

**Comment by tboffice** [comment]
あざますー出てこなかったら今のままの文章でもOKです

**Comment by syucream** [comment]
SHOW BY ROCK!! ネタ入れるのムズイっす ...  とりあえずお茶を濁す為の記述を追加しました。これはこれで中途半端感が出てしまったような。
https://github.com/nanaka-inside/C88/commit/4f42bafd55a382e15550dc5cb5bba2eee419df7d

**Comment by tboffice** [comment]
あーいいんじゃないんですかね。そのままで受領します～～
