### ISSUE TITLE
(仮)はとれるの？

### ISSUE THREAD

**Issue by tboffice** [nanaka-inside/C88#7]
- https://github.com/nanaka-inside/C88/blob/master/bob/index.md#障害起きたら朝絶対起こされるマン仮
- 個人的に取ってもok。他に良いタイトルがあれば確定よろ
- @bobmk2 
- http://codezine.jp/article/detail/8485 結構なPV数いってるからこれも宣伝すればえーじゃないの

**Comment by bobmk2** [comment]
タイトルから(仮)を外しましたー。

宣伝差し込む箇所、最初と末尾、どっちが自然ですかねー？
よしななかしょに適当に差し込んでいただけると…っ！

**Comment by tboffice** [comment]
(仮)はずし確認しました。
bob氏テキストの最後に書いておけばそのまま載っけます。そのほうが手っ取り早いと思
